-- ============================================================
-- SchoolCo — Sprint 1 Schema
-- Migration: 00005_sprint1_schema
--
-- Adds:
--   1. display_id_counters  — atomic counter table for human-readable IDs
--   2. next_org_display_id() — function to generate IDs like RLA-S0001
--   3. families             — first-class family entities
--   4. households           — per-family address units (supports split households)
--   5. ALTERs: students     — adds student_display_id, family_id
--   6. ALTERs: guardianships — adds household_id
--   7. ALTERs: organization_members — adds display_id
--   8. Triggers for auto-generating all display IDs on INSERT
--
-- Run AFTER: 00001, 00002, 00003, 00004
-- ============================================================

-- ── 1. display_id_counters ───────────────────────────────────
-- Atomic counter per (organization, prefix). Guarantees unique,
-- sequential, gap-free IDs for each entity type per org.
-- Uses ON CONFLICT DO UPDATE for concurrency safety.

create table if not exists display_id_counters (
  organization_id  uuid    not null references organizations(id) on delete cascade,
  id_prefix        text    not null,  -- 'S', 'F', 'H', 'P', 'T', 'A', 'V', 'ST', 'RG'
  last_value       integer not null default 0,
  primary key (organization_id, id_prefix)
);

comment on table display_id_counters is
  'Atomic counters for generating human-readable SchoolCo display IDs (e.g. RLA-S0001). One row per org per prefix.';

-- ── 2. next_org_display_id() ─────────────────────────────────
-- Atomically increments the counter and returns the next display ID.
-- Format: {ORG_SHORT_NAME}-{PREFIX}{ZERO_PADDED_4_DIGIT_NUMBER}
-- Example: RLA-S0001, RLA-F0001, RLA-H0001
--
-- SECURITY DEFINER so it can bypass RLS on display_id_counters.
-- Only callable from server-side triggers and server actions.

create or replace function next_org_display_id(
  p_organization_id  uuid,
  p_prefix           text
) returns text
language plpgsql
security definer
as $$
declare
  v_short_name  text;
  v_next        integer;
begin
  -- Get the org short name for the ID prefix
  select coalesce(short_name, 'ORG')
  into   v_short_name
  from   organizations
  where  id = p_organization_id;

  -- Atomically increment the counter (safe under concurrent inserts)
  insert into display_id_counters (organization_id, id_prefix, last_value)
  values (p_organization_id, p_prefix, 1)
  on conflict (organization_id, id_prefix) do update
    set last_value = display_id_counters.last_value + 1
  returning last_value into v_next;

  -- Return formatted ID: "RLA-S0001"
  return upper(v_short_name) || '-' || p_prefix || lpad(v_next::text, 4, '0');
end;
$$;

comment on function next_org_display_id(uuid, text) is
  'Atomically generates the next display ID for an org+prefix combination. Returns e.g. RLA-S0001.';

-- ── 3. families ──────────────────────────────────────────────
-- A family is the top-level grouping for students and guardians.
-- One family can have multiple households (for split-household support).
-- Students belong to a family. Guardians are linked to students
-- via the guardianships table (and optionally to a household).

create table if not exists families (
  -- Standard SchoolCo columns
  id               uuid         default uuid_generate_v4() primary key,
  organization_id  uuid         not null references organizations(id) on delete cascade,
  created_at       timestamptz  default now() not null,
  created_by       uuid         references profiles(id),
  updated_at       timestamptz  default now() not null,
  updated_by       uuid         references profiles(id),
  status           text         default 'active' not null,
  archived_at      timestamptz,
  archived_by      uuid         references profiles(id),

  -- Human-readable display ID — auto-generated by trigger
  family_display_id  text       unique,  -- e.g. "RLA-F0001"

  -- Family info
  family_name        text       not null,  -- e.g. "The Thompson Family"
  notes              text,                 -- Staff notes — never shown to parents
  is_split_household boolean    not null default false  -- Flag: multiple households
);

comment on table families is
  'Top-level family entity. Each family can have one or more households and multiple students.';
comment on column families.family_display_id is
  'Human-readable ID, auto-generated on insert. Format: {ORG}-F{NNNN}. Used in search, reports, QR badges.';
comment on column families.notes is
  'Staff-only notes about this family. Never exposed to parent or guardian sessions.';
comment on column families.is_split_household is
  'True if this family has guardians in separate households with different custody arrangements.';

create index idx_families_org         on families(organization_id);
create index idx_families_status      on families(organization_id, status) where archived_at is null;
create index idx_families_display_id  on families(family_display_id);

-- Auto-update updated_at
create trigger families_updated_at
  before update on families
  for each row execute function update_updated_at_column();

-- Auto-generate family_display_id on insert
create or replace function set_family_display_id()
returns trigger
language plpgsql
security definer
as $$
begin
  if new.family_display_id is null then
    new.family_display_id := next_org_display_id(new.organization_id, 'F');
  end if;
  return new;
end;
$$;

create trigger families_display_id
  before insert on families
  for each row execute function set_family_display_id();

-- ── 4. households ────────────────────────────────────────────
-- A household represents one physical address/home unit within a family.
-- Most families have one household. Split-household families have two or more.
-- Each household has its own address, phone, and email.
-- Guardians are associated with a household via the guardianships.household_id FK.

create table if not exists households (
  -- Standard SchoolCo columns
  id               uuid         default uuid_generate_v4() primary key,
  organization_id  uuid         not null references organizations(id) on delete cascade,
  created_at       timestamptz  default now() not null,
  created_by       uuid         references profiles(id),
  updated_at       timestamptz  default now() not null,
  updated_by       uuid         references profiles(id),
  status           text         default 'active' not null,
  archived_at      timestamptz,
  archived_by      uuid         references profiles(id),

  -- Human-readable display ID — auto-generated by trigger
  household_display_id  text    unique,  -- e.g. "RLA-H0001"

  -- Household relationship
  family_id        uuid         not null references families(id) on delete cascade,
  household_label  text         not null,  -- e.g. "Johnson Family – Primary"
  sort_order       smallint     default 1,  -- 1 = primary, 2 = secondary, etc.

  -- Contact info for this household (separate from individual guardian contacts)
  address_json     jsonb,       -- {street1, street2?, city, state, zip, country}
  phone            text,
  email            text
);

comment on table households is
  'One physical address unit within a family. Supports split-household custody arrangements.';
comment on column households.household_display_id is
  'Human-readable ID, auto-generated on insert. Format: {ORG}-H{NNNN}.';
comment on column households.sort_order is
  '1 = primary household, 2 = secondary, etc. Determines display order in staff views.';
comment on column households.address_json is
  'Physical address of this household. JSON: {street1, street2?, city, state, zip, country}.';

create index idx_households_org       on households(organization_id);
create index idx_households_family    on households(family_id);
create index idx_households_display   on households(household_display_id);

-- Auto-update updated_at
create trigger households_updated_at
  before update on households
  for each row execute function update_updated_at_column();

-- Auto-generate household_display_id on insert
create or replace function set_household_display_id()
returns trigger
language plpgsql
security definer
as $$
begin
  if new.household_display_id is null then
    new.household_display_id := next_org_display_id(new.organization_id, 'H');
  end if;
  return new;
end;
$$;

create trigger households_display_id
  before insert on households
  for each row execute function set_household_display_id();

-- ── 5. ALTER students — add display ID + family link ─────────
-- students table was created in 00004. We add:
--   student_display_id  — e.g. "RLA-S0001"
--   family_id           — links student to their family entity

alter table students
  add column if not exists student_display_id  text unique,
  add column if not exists family_id           uuid references families(id);

comment on column students.student_display_id is
  'Human-readable student ID, auto-generated on insert. Format: {ORG}-S{NNNN}. Used in QR badges, attendance, reports.';
comment on column students.family_id is
  'The family this student belongs to. All students in a family share one family record.';

create index if not exists idx_students_family       on students(family_id);
create index if not exists idx_students_display_id   on students(student_display_id);

-- Auto-generate student_display_id on insert (if not provided)
create or replace function set_student_display_id()
returns trigger
language plpgsql
security definer
as $$
begin
  if new.student_display_id is null then
    new.student_display_id := next_org_display_id(new.organization_id, 'S');
  end if;
  return new;
end;
$$;

create trigger students_display_id
  before insert on students
  for each row execute function set_student_display_id();

-- ── 6. ALTER guardianships — add household link ───────────────
-- guardianships table was created in 00004. We add:
--   household_id  — which household this guardian is associated with

alter table guardianships
  add column if not exists household_id  uuid references households(id);

comment on column guardianships.household_id is
  'The household this guardian is associated with. Null = single-household family.
   Enables split-household pickup and notification routing.';

create index if not exists idx_guardianships_household on guardianships(household_id);

-- ── 7. ALTER organization_members — add display ID ───────────
-- organization_members was created in 00001. We add:
--   display_id — role-based human-readable ID (RLA-P0001, RLA-T0001, etc.)

alter table organization_members
  add column if not exists display_id  text;

comment on column organization_members.display_id is
  'Human-readable member ID based on role. Format: {ORG}-{ROLE_PREFIX}{NNNN}.
   P = Parent, T = Teacher, A = Admin, V = Volunteer, ST = Staff, RG = Registrar.
   Auto-generated on insert.';

create unique index if not exists idx_org_members_display_id
  on organization_members(display_id)
  where display_id is not null;

-- Role-to-prefix mapping for organization_members display IDs
create or replace function member_id_prefix(p_role user_role)
returns text
language sql
immutable
as $$
  select case p_role
    when 'parent'         then 'P'
    when 'teacher'        then 'T'
    when 'admin'          then 'A'
    when 'full_admin'     then 'A'
    when 'platform_admin' then 'A'
    when 'volunteer'      then 'V'
    when 'staff'          then 'ST'
    when 'registrar'      then 'RG'
    when 'student_future' then 'SF'
    else                       'M'
  end;
$$;

comment on function member_id_prefix(user_role) is
  'Returns the display ID prefix for a given role. P=Parent, T=Teacher, A=Admin, V=Volunteer, etc.';

-- Auto-generate display_id for organization_members on insert
create or replace function set_member_display_id()
returns trigger
language plpgsql
security definer
as $$
declare
  v_prefix text;
begin
  if new.display_id is null then
    v_prefix := member_id_prefix(new.role);
    new.display_id := next_org_display_id(new.organization_id, v_prefix);
  end if;
  return new;
end;
$$;

create trigger org_members_display_id
  before insert on organization_members
  for each row execute function set_member_display_id();

-- ── Verification queries ──────────────────────────────────────
-- Run these in the SQL Editor after applying this migration:
--
-- SELECT table_name FROM information_schema.tables
-- WHERE table_schema = 'public'
-- AND table_name IN ('display_id_counters','families','households');
-- → 3 rows
--
-- SELECT column_name FROM information_schema.columns
-- WHERE table_name = 'students'
-- AND column_name IN ('student_display_id','family_id');
-- → 2 rows
--
-- SELECT column_name FROM information_schema.columns
-- WHERE table_name = 'organization_members'
-- AND column_name = 'display_id';
-- → 1 row
--
-- SELECT next_org_display_id(id, 'TEST') FROM organizations LIMIT 1;
-- → Should return e.g. "RLA-TEST0001"
