"use client";

import { useState, useTransition } from "react";
import { X, AlertTriangle, Loader2, CheckCircle, GraduationCap } from "lucide-react";
import {
  updateAcademicDocument,
  type AcademicHistoryItem,
} from "@/app/actions/documents";
import {
  ACADEMIC_RECORD_TYPE_LABELS,
  ACADEMIC_REPORTING_PERIOD_LABELS,
  ACADEMIC_RECORD_TYPES,
  ACADEMIC_REPORTING_PERIODS,
  ACADEMIC_SOURCE_OPTIONS,
  type AcademicRecordType,
  type AcademicReportingPeriod,
  type AcademicRecordSource,
} from "@/lib/documents/types";

interface Props {
  doc:       AcademicHistoryItem;
  onClose:   () => void;
  onSuccess: (updated: AcademicHistoryItem) => void;
}

const CUSTOM_YEAR = "__custom__";

function schoolYearOptions(): string[] {
  const now = new Date().getFullYear();
  const years: string[] = [];
  for (let y = now + 2; y >= now - 50; y--) {
    years.push(`${y - 1}–${y}`);
  }
  return years;
}

const SCHOOL_YEARS = schoolYearOptions();

function resolveInitialYear(year: string): { select: string; custom: string } {
  if (SCHOOL_YEARS.includes(year)) return { select: year, custom: "" };
  return { select: CUSTOM_YEAR, custom: year };
}

export function EditAcademicDocumentModal({ doc, onClose, onSuccess }: Props) {
  const [isPending, startTransition] = useTransition();
  const [error, setError]            = useState<string | null>(null);

  const init = resolveInitialYear(doc.schoolYear);

  const [title, setTitle]           = useState(doc.title);
  const [recordType, setRecordType] = useState<AcademicRecordType>(doc.recordType);
  const [schoolYear, setSchoolYear] = useState(init.select);
  const [customYear, setCustomYear] = useState(init.custom);
  const [period, setPeriod]         = useState<AcademicReportingPeriod | "">(doc.reportingPeriod ?? "");
  const [recordDate, setRecordDate] = useState(doc.recordDate ?? "");
  const [source, setSource]         = useState<AcademicRecordSource>(doc.recordSource);
  const [parentVisible, setParentVisible] = useState(doc.parentVisible);

  const effectiveYear = schoolYear === CUSTOM_YEAR ? customYear.trim() : schoolYear;

  function handleSubmit() {
    setError(null);
    if (!title.trim())          { setError("Title is required."); return; }
    if (!effectiveYear.trim())  { setError("School year is required."); return; }

    startTransition(async () => {
      const result = await updateAcademicDocument(doc.id, {
        title:           title.trim(),
        recordType,
        schoolYear:      effectiveYear,
        reportingPeriod: period === "" ? null : (period as AcademicReportingPeriod),
        recordDate:      recordDate || null,
        recordSource:    source,
        parentVisible,
      });

      if (!result.success) {
        setError(result.error ?? "Save failed.");
        return;
      }

      // Build updated item for immediate UI refresh
      const updated: AcademicHistoryItem = {
        ...doc,
        title:           title.trim(),
        recordType,
        recordTypeLabel: ACADEMIC_RECORD_TYPE_LABELS[recordType],
        schoolYear:      effectiveYear,
        reportingPeriod: period === "" ? null : (period as AcademicReportingPeriod),
        periodLabel:     period ? (ACADEMIC_REPORTING_PERIOD_LABELS[period as AcademicReportingPeriod] ?? null) : null,
        recordDate:      recordDate || null,
        recordSource:    source,
        sourceLabel:     ACADEMIC_SOURCE_OPTIONS.find(o => o.value === source)?.label ?? source,
        parentVisible,
      };
      onSuccess(updated);
    });
  }

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/40 px-4">
      <div className="w-full max-w-lg rounded-2xl bg-white shadow-xl max-h-[92vh] overflow-y-auto flex flex-col">

        {/* Header */}
        <div className="flex items-center justify-between px-6 py-4 border-b border-sc-gray-100 flex-shrink-0">
          <div>
            <p className="font-serif text-heading-2 text-sc-navy">Edit Academic Record</p>
            <p className="text-xs text-sc-gray mt-0.5">Editing metadata only — the uploaded file is unchanged.</p>
          </div>
          <button onClick={onClose} className="p-1.5 rounded-lg text-sc-gray hover:text-sc-navy hover:bg-sc-gray-50 transition-colors">
            <X className="size-5" />
          </button>
        </div>

        <div className="px-6 py-5 space-y-4 overflow-y-auto flex-1">

          {/* SchoolCo-generated warning */}
          {doc.recordSource === "schoolco_generated" && (
            <div className="flex items-start gap-2 rounded-xl bg-sc-gold-50 border border-sc-gold-300 px-3 py-2.5 text-label-sm text-sc-gold-800">
              <GraduationCap className="size-4 shrink-0 mt-0.5" />
              <span>
                This record was generated by SchoolCo. Editing metadata here does not alter the underlying grades or report data. To correct grades, use the Gradebook.
              </span>
            </div>
          )}

          {/* Title */}
          <div className="space-y-1.5">
            <label className="text-label-sm font-medium text-sc-navy">Title *</label>
            <input
              type="text"
              value={title}
              onChange={(e) => setTitle(e.target.value)}
              className="w-full rounded-lg border border-sc-gray-200 px-3 py-2 text-label-sm focus:outline-none focus:ring-2 focus:ring-sc-teal/30"
            />
          </div>

          {/* Record Type */}
          <div className="space-y-1.5">
            <label className="text-label-sm font-medium text-sc-navy">Record Type *</label>
            <select
              value={recordType}
              onChange={(e) => setRecordType(e.target.value as AcademicRecordType)}
              className="w-full rounded-lg border border-sc-gray-200 px-3 py-2 text-label-sm bg-white focus:outline-none focus:ring-2 focus:ring-sc-teal/30"
            >
              {ACADEMIC_RECORD_TYPES.map((t) => (
                <option key={t} value={t}>{ACADEMIC_RECORD_TYPE_LABELS[t]}</option>
              ))}
            </select>
          </div>

          {/* School Year + Period */}
          <div className="grid grid-cols-2 gap-3">
            <div className="space-y-1.5">
              <label className="text-label-sm font-medium text-sc-navy">School Year *</label>
              <select
                value={schoolYear}
                onChange={(e) => setSchoolYear(e.target.value)}
                className="w-full rounded-lg border border-sc-gray-200 px-3 py-2 text-label-sm bg-white focus:outline-none focus:ring-2 focus:ring-sc-teal/30"
              >
                {SCHOOL_YEARS.map((y) => (
                  <option key={y} value={y}>{y}</option>
                ))}
                <option value={CUSTOM_YEAR}>Other / Custom…</option>
              </select>
              {schoolYear === CUSTOM_YEAR && (
                <input
                  type="text"
                  value={customYear}
                  onChange={(e) => setCustomYear(e.target.value)}
                  placeholder="e.g. 1998–1999"
                  className="w-full rounded-lg border border-sc-gray-200 px-3 py-2 text-label-sm focus:outline-none focus:ring-2 focus:ring-sc-teal/30"
                />
              )}
            </div>
            <div className="space-y-1.5">
              <label className="text-label-sm font-medium text-sc-navy">
                Period
                <span className="ml-1 font-normal text-sc-gray text-xs">(opt.)</span>
              </label>
              <select
                value={period}
                onChange={(e) => setPeriod(e.target.value as AcademicReportingPeriod | "")}
                className="w-full rounded-lg border border-sc-gray-200 px-3 py-2 text-label-sm bg-white focus:outline-none focus:ring-2 focus:ring-sc-teal/30"
              >
                <option value="">— None —</option>
                {ACADEMIC_REPORTING_PERIODS.map((p) => (
                  <option key={p} value={p}>{ACADEMIC_REPORTING_PERIOD_LABELS[p]}</option>
                ))}
              </select>
            </div>
          </div>

          {/* Record Date */}
          <div className="space-y-1.5">
            <label className="text-label-sm font-medium text-sc-navy">
              Record Date
              <span className="ml-1 font-normal text-sc-gray text-xs">(date on the document — optional)</span>
            </label>
            <input
              type="date"
              value={recordDate}
              onChange={(e) => setRecordDate(e.target.value)}
              className="w-full rounded-lg border border-sc-gray-200 px-3 py-2 text-label-sm focus:outline-none focus:ring-2 focus:ring-sc-teal/30"
            />
          </div>

          {/* Record Source */}
          <div className="space-y-1.5">
            <label className="text-label-sm font-medium text-sc-navy">Record Source</label>
            <select
              value={source}
              onChange={(e) => setSource(e.target.value as AcademicRecordSource)}
              className="w-full rounded-lg border border-sc-gray-200 px-3 py-2 text-label-sm bg-white focus:outline-none focus:ring-2 focus:ring-sc-teal/30"
            >
              {ACADEMIC_SOURCE_OPTIONS.map((s) => (
                <option key={s.value} value={s.value}>{s.label}</option>
              ))}
            </select>
          </div>

          {/* Parent Visibility */}
          <label className="flex items-start gap-3 rounded-xl border border-sc-gray-100 p-3 cursor-pointer hover:bg-sc-gray-50 transition-colors">
            <input
              type="checkbox"
              checked={parentVisible}
              onChange={(e) => setParentVisible(e.target.checked)}
              className="mt-0.5 accent-sc-teal"
            />
            <div>
              <p className="text-label-sm font-medium text-sc-navy">Visible to Parent</p>
              <p className="text-xs text-sc-gray mt-0.5">Parent can view this from the portal.</p>
            </div>
          </label>

          {error && (
            <div className="rounded-xl border border-sc-rose-200 bg-sc-rose-50 p-3 flex items-start gap-2">
              <AlertTriangle className="size-4 text-sc-rose mt-0.5 flex-shrink-0" />
              <p className="text-xs text-sc-rose">{error}</p>
            </div>
          )}
        </div>

        {/* Footer */}
        <div className="px-6 py-4 border-t border-sc-gray-100 flex justify-end gap-2 flex-shrink-0">
          <button
            onClick={onClose}
            disabled={isPending}
            className="rounded-lg border border-sc-gray-200 px-4 py-2 text-label-sm text-sc-gray hover:bg-sc-gray-50 disabled:opacity-40 transition-colors"
          >
            Cancel
          </button>
          <button
            onClick={handleSubmit}
            disabled={isPending}
            className="rounded-lg bg-sc-teal px-4 py-2 text-label-sm text-white hover:bg-sc-teal-700 disabled:opacity-50 transition-colors flex items-center gap-1.5"
          >
            {isPending ? <><Loader2 className="size-3.5 animate-spin" /> Saving…</> : "Save Changes"}
          </button>
        </div>
      </div>
    </div>
  );
}
